#!/bin/sh
set -e
. /etc/wifi.env

case "$1" in
    start)
    	mkdir -p /var/run/wpa_supplicant
        cat > /etc/wpa_supplicant.conf <<EOF
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1
country=US

network={
    ssid="$SSID1"
    psk="$PSK1"
    proto=RSN
    key_mgmt=WPA-PSK
    pairwise=CCMP
    auth_alg=OPEN
    priority=10
}

network={
    ssid="$SSID2"
    psk="$PSK2"
    proto=RSN
    key_mgmt=WPA-PSK
    pairwise=CCMP
    auth_alg=OPEN
    priority=5
}
EOF
        ifup wlan0 || exit 1
        ;;
    stop)
        ifdown wlan0 || exit 1
        ;;
    restart|reload)
        $0 stop
        $0 start
        ;;
    status)
        ip addr show wlan0
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0

